// Autogenerated from Pigeon (v0.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString*, id>* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface CcppPaymentCode ()
+(CcppPaymentCode*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface MakeTokenizedCreditCardPaymentInput ()
+(MakeTokenizedCreditCardPaymentInput*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface CcppPaymentResponse ()
+(CcppPaymentResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation CcppPaymentCode
+(CcppPaymentCode*)fromMap:(NSDictionary*)dict {
  CcppPaymentCode* result = [[CcppPaymentCode alloc] init];
  result.code = dict[@"code"];
  if ((NSNull *)result.code == [NSNull null]) {
    result.code = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.code ? self.code : [NSNull null]), @"code", nil];
}
@end

@implementation MakeTokenizedCreditCardPaymentInput
+(MakeTokenizedCreditCardPaymentInput*)fromMap:(NSDictionary*)dict {
  MakeTokenizedCreditCardPaymentInput* result = [[MakeTokenizedCreditCardPaymentInput alloc] init];
  result.paymentToken = dict[@"paymentToken"];
  if ((NSNull *)result.paymentToken == [NSNull null]) {
    result.paymentToken = nil;
  }
  result.paymentCode = [CcppPaymentCode fromMap:dict[@"paymentCode"]];
  if ((NSNull *)result.paymentCode == [NSNull null]) {
    result.paymentCode = nil;
  }
  result.cardToken = dict[@"cardToken"];
  if ((NSNull *)result.cardToken == [NSNull null]) {
    result.cardToken = nil;
  }
  result.securityCode = dict[@"securityCode"];
  if ((NSNull *)result.securityCode == [NSNull null]) {
    result.securityCode = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.paymentToken ? self.paymentToken : [NSNull null]), @"paymentToken", (self.paymentCode ? [self.paymentCode toMap] : [NSNull null]), @"paymentCode", (self.cardToken ? self.cardToken : [NSNull null]), @"cardToken", (self.securityCode ? self.securityCode : [NSNull null]), @"securityCode", nil];
}
@end

@implementation CcppPaymentResponse
+(CcppPaymentResponse*)fromMap:(NSDictionary*)dict {
  CcppPaymentResponse* result = [[CcppPaymentResponse alloc] init];
  result.responseCode = dict[@"responseCode"];
  if ((NSNull *)result.responseCode == [NSNull null]) {
    result.responseCode = nil;
  }
  result.redirectUrl = dict[@"redirectUrl"];
  if ((NSNull *)result.redirectUrl == [NSNull null]) {
    result.redirectUrl = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.responseCode ? self.responseCode : [NSNull null]), @"responseCode", (self.redirectUrl ? self.redirectUrl : [NSNull null]), @"redirectUrl", nil];
}
@end

void CcppApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<CcppApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CcppApi.setupProduction"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api setupProduction:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CcppApi.setupSandbox"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api setupSandbox:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CcppApi.makeTokenizedCreditCardPayment"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        MakeTokenizedCreditCardPaymentInput *input = [MakeTokenizedCreditCardPaymentInput fromMap:message];
        [api makeTokenizedCreditCardPayment:input completion:^(CcppPaymentResponse *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult([output toMap], error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
